import React from 'react';
import {
  DashboardOutlined,
  UserOutlined,
  TeamOutlined,
  CalendarOutlined,
  MedicineBoxOutlined,
  BarChartOutlined,
  SettingOutlined,
  ScheduleOutlined,
  HeartOutlined,
  FileTextOutlined,
  ShoppingOutlined,
  InboxOutlined,
  AssessmentOutlined,
  UserAddOutlined,
  PlusCircleOutlined,
  TodayOutlined,
  MedicineOutlined,
  GroupOutlined,
  CheckCircleOutlined,
  BookOutlined,
  FolderOpenOutlined,
  DollarOutlined,
  SearchOutlined,
  ClockCircleOutlined,
  WarningOutlined,
  LogoutOutlined,
  BulbOutlined,
  BulbFilled,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  EyeInvisibleOutlined,
  EyeTwoTone,
  LockOutlined,
  MailOutlined,
  PhoneOutlined,
  EnvironmentOutlined,
  IdcardOutlined,
  SafetyCertificateOutlined,
  ApartmentOutlined,
  AuditOutlined,
  BankOutlined
} from '@ant-design/icons';

export const getAntdIcon = (iconName) => {
  const icons = {
    dashboard: <DashboardOutlined />,
    person: <UserOutlined />,
    people: <TeamOutlined />,
    calendar_today: <CalendarOutlined />,
    local_hospital: <MedicineBoxOutlined />,
    analytics: <BarChartOutlined />,
    settings: <SettingOutlined />,
    schedule: <ScheduleOutlined />,
    personal_injury: <HeartOutlined />,
    medical_services: <MedicineBoxOutlined />,
    description: <FileTextOutlined />,
    folder: <FileTextOutlined />,
    receipt: <ShoppingOutlined />,
    inventory: <InboxOutlined />,
    assessment: <AssessmentOutlined />,
    person_add: <UserAddOutlined />,
    add_circle: <PlusCircleOutlined />,
    today: <TodayOutlined />,
    medication: <MedicineOutlined />,
    groups: <GroupOutlined />,
    event_available: <CheckCircleOutlined />,
    book_online: <BookOutlined />,
    folder_open: <FolderOpenOutlined />,
    payments: <DollarOutlined />,
    search: <SearchOutlined />,
    pending_actions: <ClockCircleOutlined />,
    inventory_2: <InboxOutlined />,
    warning: <WarningOutlined />,
    logout: <LogoutOutlined />,
    light_mode: <BulbOutlined />,
    dark_mode: <BulbFilled />,
    menu_fold: <MenuFoldOutlined />,
    menu_unfold: <MenuUnfoldOutlined />,
    lock: <LockOutlined />,
    mail: <MailOutlined />,
    phone: <PhoneOutlined />,
    environment: <EnvironmentOutlined />,
    idcard: <IdcardOutlined />,
    certificate: <SafetyCertificateOutlined />,
    apartment: <ApartmentOutlined />,
    audit: <AuditOutlined />,
    bank: <BankOutlined />
  };

  return icons[iconName] || <DashboardOutlined />;
};